#!/bin/sh
#
# git post-update hook

set -e
set -x

GITDIR=/srv/ipol/demo
TMPDIR=/media/tmp
INITSCRIPT=/etc/init.d/ipol-demo

# folders should be group-writable
umask 0002

# stop the service
sudo $INITSCRIPT stop
# update the source
git checkout -f
# remove the unused files
git clean -fd
# start the service
sudo $INITSCRIPT start
